# docker-compose.yml
networks:
  my_network:
    driver: bridge

services:
  db:
    image: postgres:16
    container_name: motivora-db
    environment:
      POSTGRES_USER: motivora-db-user
      POSTGRES_PASSWORD: BNH1271q
      POSTGRES_DB: motivoradb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    build: .
    container_name: motivora-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: motivora-db-user
      DB_PASSWORD: BNH1271q
      DB_NAME: motivoradb
      DB_SSLMODE: disable
    depends_on:
      - db
    restart: on-failure
    networks:
      - my_network

volumes:
  postgres_data: